### ISSUE TITLE
Translate "Getting R to Print English Error Messages" to Spanish

### ISSUE THREAD

**Issue by dernapo** [thomas-neitmann/thomas-adventuRe#17]
Transform a ggplot2 axis to a percentage scale
@dernapo

**Comment by thomas-neitmann** [comment]
It seems @oranwutang has already created an issue for that. Let's not duplicate efforts.

**Comment by oranwutang** [comment]
It's fine for me if @dernapo translates this post, I haven't started to do it yet.
Well, while you decide who translates this post I'll take charge of another post translation :)

**Comment by dernapo** [comment]
Ups! I will take another one.. I have changed the tittle of this issue, I will take care of "Getting R to Print English Error Messages". A small one, perfect to start ;)

**Comment by dernapo** [comment]
I guess the Label "duplicate" doesnt apply anymore.. maybe @thomas-neitmann can update it..

I do not how to create a new branch.. can someone help me? ;)

I have cloned the whole repository "thomas-adventuRe" and now I am work on it [here](https://github.com/dernapo/thomas-adventuRe). Hope is ok..

Thanks for your help here, it is my first time ;)

**Comment by thomas-neitmann** [comment]
Thanks for taking this on @dernapo! I just removed the "duplicate" label. Also you forming the whole repository is fine 👍
